services:
  # Relational DB for User Auth and Device Config
  # postgres-db:
  #   image: postgres:15
  #   container_name: smarthome-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin_password
  #     POSTGRES_DB: smarthome_auth
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  
  mongo-db:
    image: mongo:latest
    container_name: smarthome-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongodb/data
  
  # MQTT Broker for local testing (optional, can use HiveMQ Cloud instead)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: local-mqtt
    ports:
      - "1883:1883"      # Standard MQTT port
      - "9001:9001"      # MQTT over WebSockets (for your Mobile App later)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
volumes:
  pgdata:
  mongodata: